---
title: "Dissemination"

---


To be updated.

<p>&nbsp;</p>



### First-author publications

[2019]

- <a href="https://www.injuryjournal.com/article/S0020-1383(18)30788-5/fulltext" target="_blank">
**Impact of comorbidity on the association between surgery delay and mortality in hip fracture patients: a Danish nationwide cohort study.**</a>
&#214;zt&#252;rk, Buket; Johnsen, S&#248;ren Paaske; R&#246;ck, Niels Dieter; Pedersen, Lars; Pedersen, Alma Becic.
*I: Injury, Bind 50, Nr. 2, 02.2019, s. 424-431.*  


<p>&nbsp;</p>
<p>&nbsp;</p>


### Co-author publications

[2020]


- <a href="https://breast-cancer-research.biomedcentral.com/articles/10.1186/s13058-020-01337-z" target="_blank">
**Incidence of hypothyroidism after treatment for breast cancer-a Danish matched cohort study.**</a>
Falstie-Jensen, Anne Mette; Esen, Buket; Kj&aelig;rsgaard, Anders; Lorenzen, Ebbe L.; Jensen, Jeanette D.; Reinertsen, Kristin V.; Dekkers, Olaf M.; Ewertz, Marianne; Cronin-Fenton, Deirdre P.
*I: Breast Cancer Research, Bind 22, 106, 10.2020.*


- <a href="https://www.dovepress.com/validation-of-an-algorithm-to-ascertain-late-breast-cancer-recurrence--peer-reviewed-article-CLEP" target="_blank">
**Validation of an algorithm to ascertain late breast cancer recurrence using danish medical registries.**</a>
Pedersen, Rikke N&#248;rgaard; &#214;zt&#252;rk, Buket; Mellemkj&aelig;r, Lene; Friis, S&#248;ren; Tramm, Trine; N&#248;rgaard, Mette; Cronin-Fenton, Deirdre P.
*I: Clinical epidemiology, Bind 12, 10.2020, s. 1083-1093.*


- <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/pds.5088" target="_blank">
**In utero opioid exposure and risk of infections in childhood : A multinational Nordic cohort study.**</a>
Mahic, Milada; Hernandez-Diaz, Sonia; Wood, Mollie; Kieler, Helle; Odsbu, Ingvild; Norgaard, Mette; &#214;zt&#252;rk, Buket; Bateman, Brian T.; Hjellvik, Vidar; Skurtveit, Svetlana; Handal, Marte.
*I: Pharmacoepidemiology and Drug Safety, 08.2020.*


- <a href="https://bmcgeriatr.biomedcentral.com/articles/10.1186/s12877-020-01599-4" target="_blank">
**Readmission of older acutely admitted medical patients after short-term admissions in Denmark : a nationwide cohort study.**</a>
Klinge, M.; Aasbrenn, M.; &#214;zt&#252;rk, B.; Christiansen, C. F.; Suetta, C.; Pressel, E.; Nielsen, F. E.
*I: BMC Geriatrics, Bind 20, 203, 06.2020.*


- <a href="https://academic.oup.com/aje/article/189/4/277/5695267t" target="_blank">
**Hospital Records of Pain, Fatigue, or Circulatory Symptoms in Girls Exposed to Human Papillomavirus Vaccination : Cohort, Self-controlled Case Series, and Population Time Trend Studies.**</a>
Thomsen, Reimar Wernich; &#214;zt&#252;rk, Buket; Pedersen, Lars; Nicolaisen, Sia Kromann; Petersen, Irene; Olsen, J&#248;rn; S&#248;rensen, Henrik Toft.
*I: American Journal of Epidemiology, Bind 189, Nr. 4, 04.2020, s. 277-285.*



- <a href="https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2769621" target="_blank">
**Association of Neighborhood Disadvantage With Cardiovascular Risk Factors and Events Among Refugees in Denmark.** </a>
Hamad, Rita; &#214;zt&#252;rk, Buket; Foverskov, Else; Pedersen, Lars; S&#248;rensen, Henrik T.; B&#248;tker, Hans E.; White, Justin S.
*I: JAMA network open, Bind 3, Nr. 8, e2014196, 2020.*




[2019]

- <a href="https://ashpublications.org/bloodadvances/article/3/20/2980/381152/Occurrence-thromboembolic-risk-and-mortality-in" target="_blank">
**Occurrence, thromboembolic risk, and mortality in Danish patients with cold agglutinin disease.** </a>
Bylsma, Lauren C.; Ording, Anne Gulbech; Rosenthal, Adam; &#214;zt&#252;rk, Buket; Fryzek, Jon P.; Arias, Jaime Morales; R&#246;th, Alexander; Berentsen, Sigbj&#248;rn.
*I: Blood Advances, Bind 3, Nr. 20, 10.2019, s. 2980-2985.*



- <a href="https://www.ahajournals.org/doi/10.1161/JAHA.118.009528" target="_blank">
**Education of Migrant and Nonmigrant Patients Is Associated With Initiation and Discontinuation of Preventive Medications for Acute Coronary Syndrome.** </a>
Frederiksen, Hanne Winther; Zwisler, Ann Dorthe; Johnsen, S&#248;ren Paaske; &#214;zt&#252;rk, Buket; Lindhardt, Tove; Norredam, Marie.
*I: Journal of the American Heart Association, Bind 8, Nr. 11, e009528, 04.06.2019.*




- <a href="https://academic.oup.com/ageing/article/48/2/278/5274647" target="_blank">
**Regaining pre-fracture basic mobility status after hip fracture and association with post-discharge mortality and readmission-a nationwide register study in Denmark.**</a>
Kristensen, Morten Tange; &#214;zt&#252;rk, Buket; R&#246;ck, Niels Dieter; Ingeman, Annette; Palm, Henrik; Pedersen, Alma B.
*I: Age and Ageing, Bind 48, Nr. 2, 03.2019, s. 278-284.*




- <a href="https://alz-journals.onlinelibrary.wiley.com/doi/full/10.1016/j.dadm.2018.12.003" target="_blank">
**What outcomes are important to patients with mild cognitive impairment or Alzheimer's disease, their caregivers, and health-care professionals? A systematic review.** </a> 
Tochel, Claire; Smith, Michael; Baldwin, Helen; Gustavsson, Anders; Ly, Amanda; Bexelius, Christin; Nelson, Mia; Bintener, Christophe; Fantoni, Enrico; Garre-Olmo, Josep; Janssen, Olin; Jindra, Christoph; J&#248;rgensen, Isabella F.; McKeown, Alex; &#214;zt&#252;rk, Buket; Ponjoan, Anna; Potashman, Michele H.; Reed, Catherine; Roncancio-Diaz, Emilse; Vos, Stephanie; Sudlow, Cathie.
*I: Alzheimer's & Dementia, Bind 11, 2019, s. 231-247.*


[2018]

-  <a href="https://academic.oup.com/eurheartj/article/39/25/2356/4990522" target="_blank">
**Differences in initiation and discontinuation of preventive medications and use of non-pharmacological interventions after acute coronary syndrome among migrants and Danish-born.**</a>
Frederiksen, Hanne Winther; Olsen Zwisler, Ann-Dorthe; Johnsen, S&#248;ren Paaske; &#214;zt&#252;rk, Buket; Lindhardt, Tove; N&#248;rredam, Marie.
*I: European Heart Journal, Bind 39, Nr. 25, 30.04.2018, s. 2356.*



- <a href="https://www.tandfonline.com/doi/full/10.1080/0284186X.2018.1503420" target="_blank">
**KRAS mutation status, comorbidity, and mortality in patients with metastatic colorectal cancer in Denmark.** </a> 
Ording, Anne Gulbech; &#214;zt&#252;rk, Buket; Spindler, Karen-Lise Garm; S&#248;rensen, Henrik Toft; McCusker, Margaret; Ehrenstein, Vera.
*I: Acta oncologica (Stockholm, Sweden), Bind 57, Nr. 12, 2018, s. 1727-1729.*



<p>&nbsp;</p>
<p>&nbsp;</p>



### Conference contributions


[2020]


- **Oral presentation at the 36th International Conference on Pharmacoepidemiology & Therapeutic Risk Management (ICPE)**, Virtual, September 16-17, 2020.
Is your sibling design biased?.
Buket &#214;zt&#252;rk, Vera Ehrenstein, Henrik T. S&#248;rensen and Lars Pedersen.
<a href="https://onlinelibrary.wiley.com/doi/10.1002/pds.5114" target="_blank">
[Abstract] </a>



- **Flash talk at PhD day Aarhus University 2020**, Aarhus, Denmark, January 24, 2020.
Prenatal exposure to antidepressants and the risk of attention deficit hyperactivity disorder in childhood: Findings from a nationwide cohort study.
B. &#214;zt&#252;rk, L. Pedersen, V. Ehrenstein, H.T. S&#248;rensen.
<a href="https://phd.health.au.dk/fileadmin/grads.au.dk/HE/PhD_Day_2020/Programme_and_abstract_book_final_2.pdf" target="_blank">
[Abstract] </a>


[2019]


- **Oral presentation at the 35th International Conference on Pharmacoepidemiology & Therapeutic Risk Management (ICPE)**, Pennsylvania Convention Center, Philadelphia, PA, USA, August 24-28, 2019.
Exposure to Antidepressants during Pregnancy and the Risk of Attention Deficit Hyperactivity Disorder in Offspring: Findings from a Nationwide Cohort Study with and without Sibling Design.
Buket &#214;zt&#252;rk, Lars Pedersen, Vera Ehrenstein and Henrik T. S&#248;rensen.
<a href="https://onlinelibrary.wiley.com/doi/10.1002/pds.4864" target="_blank">
[Abstract] </a>

[2017]


- **Oral presentation at Dansk Ortop&#230;disk Selskab (DOS) Kongressen 2017**, Radisson Blu Scandinavia Hotel, Copenhagen, Denmark, October 25-27, 2017. 
Impact of comorbidity on the association between surgery delay and mortality in hip fracture patients: a Danish nationwide cohort study.
Buket &#214;zt&#252;rk, S&#248;ren P. Johnsen, Niels Dieter R&#246;ck, and Alma B. Pedersen.
<a href="http://abstract.ortopaedi.dk/bulletin/2017/HTMLabstract/?p=68" target="_blank">
[Abstract] </a>




