---
title: "My PhD project"
---

Here is a short description of my PhD project.

### Background

A frequently used design in epidemiologic studies is the classical cohort design, where unexposed represent the counterfactual experience of the exposed in the absence of the exposure. An alternative design that controls for potential unmeasured confounding is the sibling design. In this design, the counterfactual disease experience of the exposed subjects is represented by their unexposed siblings. By this, the estimate of the causal contrast is free from confounding by time independent traits shared by the siblings that may be difficult or impossible to measure in a given study, such as rearing practices, socioeconomic characteristics, or genetics.

Researchers often conduct a classical cohort design and a sibling design to estimate the same causal contrast. In most, studies the two estimates differ, prompting the conclusion that the estimate of the causal contrast from the sibling design is closer to the true causal contrast by virtue of better control of unmeasured confounding. 

The sibling design is, however, subject to several potential biases:

*First*, if siblings are more similar with regard to the exposure than with regard to non‐shared unmeasured confounders, the estimate of the causal contrast in the sibling design will always be more biased than the estimate of the causal contrast in the classical cohort design. 

*Second*, the dilution of the estimates due to misclassification in exposure will be greater in the sibling design than in the classical cohort design. 

*Third*, the analysis of sibling design assumes independence of the exposure and outcome status of the siblings (no sibling carryover), although that may not always be the case. 

*Finally*, the estimate of the causal contrast in a sibling design is a measure of the direct causal effect, since the design also controls for mediators that are shared by the siblings, while the estimate of the causal contrast in the classical cohort design is a measure of the total causal effect, which consists of the direct and the mediated effect. Thus, the estimates of the causal contrast from the two designs may not always be comparable.

The existing methodological studies regarding sibling design are dealing with these potential biases from a theoretical perspective. No study, to our knowledge, has addressed these potential biases of the sibling design in relation to observational studies. It is thus a major question of interest, whether the reported estimates from the sibling design in various studies are unconfounded estimates of the true causal contrasts.

In summary, the attenuation of association in a sibling design is often attributed to removal of unmeasured confounding, but this interpretation may be naïve. Therefore, we aim to investigate the sibling design from a methodological perspective in relation to observational data. We will take starting point in the clinical question: does use of antidepressants during pregnancy have a causal effect on the risk of attention deficit hyperactivity disorder (ADHD) in offspring? 


### Aims of the project
The specific aims are to:

* Examine the impacts of non-shared unmeasured confounding, misclassification, sibling carryover and mediators on the sibling design.

*	Examine the causal contrast of antidepressants use during pregnancy and the risk of ADHD in offspring by using a classical cohort design and a sibling design.

*	Explore the performance of the sibling design beyond the case of antidepressants and ADHD. 
